use super::reflection::TypeDescriptor;

// =============================================================================
// JsonFlavor
// =============================================================================

/// Controls the JSON output format produced by [`Serializer::to_json`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum JsonFlavor {
    /// Compact output with no extra whitespace.
    Dense,
    /// Human-readable output with newlines and indentation.
    Readable,
}

// =============================================================================
// UnrecognizedValuesPolicy
// =============================================================================

/// Controls whether unrecognized fields/variants are preserved during
/// deserialization.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UnrecognizedValues {
    /// Preserve unrecognized fields and variants (forward-compatibility mode).
    Keep,
    /// Discard unrecognized fields and variants.
    Drop,
}

// =============================================================================
// Serializer
// =============================================================================

/// Serialises and deserialises values of type `T` in both JSON and binary
/// formats.
pub struct Serializer<T: 'static> {
    adapter: AdapterRef<T>,
}

impl<T: 'static> Clone for Serializer<T> {
    fn clone(&self) -> Self {
        Self { adapter: self.adapter.clone() }
    }
}

impl<T: 'static> std::fmt::Debug for Serializer<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Serializer").finish_non_exhaustive()
    }
}

impl<T: 'static> Serializer<T> {
    /// Serialises `v` to a JSON string.
    ///
    /// Pass [`JsonFlavor::Readable`] for human-readable (indented) output;
    /// [`JsonFlavor::Dense`] produces compact JSON.
    pub fn to_json(&self, v: &T, flavor: JsonFlavor) -> String {
        let mut out = String::new();
        match flavor {
            JsonFlavor::Readable => self.adapter.get().to_json(v, Some("\n"), &mut out),
            JsonFlavor::Dense => self.adapter.get().to_json(v, None, &mut out),
        }
        out
    }

    /// Deserialises a JSON string into a value of type `T`.
    ///
    /// Use [`UnrecognizedValuesPolicy::KeepUnrecognized`] to preserve
    /// fields/variants from a newer schema version.
    pub fn from_json(
        &self,
        code: &str,
        policy: UnrecognizedValues,
    ) -> Result<T, String> {
        let fv: serde_json::Value =
            serde_json::from_str(code).map_err(|e| e.to_string())?;
        self.adapter.get().from_json(&fv, policy == UnrecognizedValues::Keep)
    }

    /// Serialises `v` to the Skir binary wire format.
    ///
    /// The returned bytes are prefixed with the four-byte magic `"skir"`.
    pub fn to_bytes(&self, v: &T) -> Vec<u8> {
        let mut out = b"skir".to_vec();
        self.adapter.get().encode(v, &mut out);
        out
    }

    /// Deserialises a value from the Skir binary wire format.
    ///
    /// If `bytes` lacks the `"skir"` prefix the payload is treated as a UTF-8
    /// JSON string and parsed via [`Self::from_json`].
    ///
    /// Use [`UnrecognizedValuesPolicy::KeepUnrecognized`] to preserve
    /// fields/variants from a newer schema version.
    pub fn from_bytes(
        &self,
        bytes: &[u8],
        policy: UnrecognizedValues,
    ) -> Result<T, String> {
        let keep = policy == UnrecognizedValues::Keep;
        if bytes.starts_with(b"skir") {
            let mut rest = &bytes[4..];
            self.adapter.get().decode(&mut rest, keep)
        } else {
            let s = std::str::from_utf8(bytes).map_err(|e| e.to_string())?;
            self.from_json(s, policy)
        }
    }

    /// Returns a [`TypeDescriptor`] that describes the schema of `T`.
    pub fn type_descriptor(&self) -> TypeDescriptor {
        self.adapter.get().type_descriptor()
    }
    /// Constructs a `Serializer` that owns `adapter`.
    ///
    /// For use only by code generated by the Skir code generator.
    pub(super) fn new(adapter: impl TypeAdapter<T> + 'static) -> Self {
        Self { adapter: AdapterRef::Owned(Box::new(adapter)) }
    }

    /// Constructs a `Serializer` that borrows a `'static` adapter reference
    /// (e.g. a reference to a `static` item).
    ///
    /// For use only by code generated by the Skir code generator.
    pub(super) fn new_borrowed(adapter: &'static dyn TypeAdapter<T>) -> Self {
        Self { adapter: AdapterRef::Borrowed(adapter) }
    }

    /// Returns a reference to the underlying [`TypeAdapter`].
    pub(super) fn adapter(&self) -> &dyn TypeAdapter<T> {
        self.adapter.get()
    }

}

/// Owned or `'static`-borrowed reference to a `dyn TypeAdapter<T>`.
///
/// Serves the same purpose as `Cow<'static, A>` would, but works with unsized
/// trait objects (which cannot satisfy `ToOwned`).
enum AdapterRef<T: 'static> {
    Owned(Box<dyn TypeAdapter<T>>),
    Borrowed(&'static dyn TypeAdapter<T>),
}

impl<T: 'static> Clone for AdapterRef<T> {
    fn clone(&self) -> Self {
        match self {
            Self::Owned(b) => Self::Owned(b.clone_box()),
            Self::Borrowed(r) => Self::Borrowed(*r),
        }
    }
}

impl<T: 'static> AdapterRef<T> {
    fn get(&self) -> &dyn TypeAdapter<T> {
        match self {
            Self::Owned(b) => b.as_ref(),
            Self::Borrowed(r) => *r,
        }
    }
}

// =============================================================================
// TypeAdapter
// =============================================================================

/// Internal interface implemented by every concrete adapter
/// (primitive, array, optional, struct, enum).
///
/// Only adapters defined inside this crate can satisfy it.
/// For use only by code generated by the Skir code generator.
pub(super) trait TypeAdapter<T>: Send + Sync {
    /// Returns `true` when `input` is the default (zero) value for `T`.
    fn is_default(&self, input: &T) -> bool;

    /// Writes the JSON representation of `input` to `out`.
    ///
    /// `eol_indent` is `None` for dense (compact) output. In readable (indented)
    /// mode it is `Some` with a string composed of `"\n"` followed by the
    /// indentation prefix for the current nesting level.
    fn to_json(&self, input: &T, eol_indent: Option<&str>, out: &mut String);

    /// Deserialises a [`serde_json::Value`] into `T`.
    ///
    /// Set `keep_unrecognized_values` to preserve fields/variants from a newer
    /// schema version that are not recognised by this decoder.
    fn from_json(
        &self,
        json: &serde_json::Value,
        keep_unrecognized_values: bool,
    ) -> Result<T, String>;

    /// Serialises `input` to the Skir binary wire format, appending bytes to `out`.
    fn encode(&self, input: &T, out: &mut Vec<u8>);

    /// Deserialises a value from the Skir binary wire format, advancing the
    /// slice past the bytes consumed.
    ///
    /// Set `keep_unrecognized_values` to preserve fields/variants from a newer
    /// schema version.
    fn decode(
        &self,
        input: &mut &[u8],
        keep_unrecognized_values: bool,
    ) -> Result<T, String>;

    /// Returns a [`TypeDescriptor`] that describes the schema of `T`.
    fn type_descriptor(&self) -> TypeDescriptor;

    /// Returns a boxed clone of this adapter.
    fn clone_box(&self) -> Box<dyn TypeAdapter<T>>;
}
