import {
  type CodeGenerator,
  type Constant,
  type Doc,
  type Field,
  type Method,
  type RecordKey,
  type RecordLocation,
  type ResolvedType,
  convertCase,
} from "skir-internal";
import { z } from "zod";
import { getTypeName, toStructFieldName } from "./naming.js";
import { collectRustModuleSpecs, RustModuleSpec } from "./rust_module_spec.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

class RustCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-rust-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap, config } = input;
    const outputFiles: CodeGenerator.OutputFile[] = [];
    const rustModuleSpecs = collectRustModuleSpecs(input.modules);
    for (const moduleSpec of rustModuleSpecs) {
      outputFiles.push({
        path: moduleSpec.path,
        code: new RustSourceFileGenerator(
          moduleSpec,
          recordMap,
          config,
        ).generate(),
      });
    }
    return { files: outputFiles };
  }
}

// Generates the code for one Rust file.
class RustSourceFileGenerator {
  constructor(
    private readonly moduleSpec: RustModuleSpec,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
    private readonly config: Config,
  ) {
    this.typeSpeller = new TypeSpeller(recordMap, moduleSpec.skirModule?.path);
  }

  generate(): string {
    // const packageName = skirModulePathToSkiroutPath(this.inModule.path);

    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.push(
      `#![allow(nonstandard_style)]

      //  ______                        _               _  _  _
      //  |  _  \\                      | |             | |(_)| |
      //  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
      //  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _\` || || __|
      //  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_ 
      //  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|
      //
      // Generated by skir-rust-gen
      // Home: https://github.com/gepheum/skir-rust-gen
      //
      // To install the Skir client library, run:
      //   cargo add skir-rust-client
      `,
    );

    for (const childModuleName of this.moduleSpec.childModuleNames) {
      this.push(`pub mod ${childModuleName};\n`);
    }

    this.push("\n");

    const skirModule = this.moduleSpec.skirModule;
    if (skirModule) {
      for (const record of skirModule.records) {
        const { recordType } = record.record;
        if (recordType === "struct") {
          this.writeStruct(record);
        } else {
          this.writeEnum(record);
        }
      }

      if (skirModule.methods.length) {
        this.pushSeparator("Methods");
        for (const method of skirModule.methods) {
          this.writeMethod(method);
        }
      }

      if (skirModule.constants.length) {
        this.pushSeparator("Constants");
        for (const constant of skirModule.constants) {
          this.writeConstant(constant);
        }
      }
    }

    return this.joinLinesAndFixFormatting();
  }

  // private writeImports(): void {
  //   this.push(`import (
  //     "github.com/gepheum/skir-go-client"
  //     "sync/atomic"
  //     "time"
  //   `);
  //   for (const importedPath of Object.keys(this.inModule.pathToImportedNames)) {
  //     const alias = modulePathToAlias(importedPath);
  //     const packagePath = modulePathToPackagePath(importedPath);
  //     this.push(
  //       `${alias} "${this.config.goModuleName}/skirout/${packagePath}"\n`,
  //     );
  //   }
  //   this.push(")\n\n");
  // }

  private writeStruct(struct: RecordLocation): void {
    const typeName = getTypeName(struct);
    this.push(`#[derive(std::clone::Clone)]\n`);
    this.push(`pub struct ${typeName} {\n`);
    for (const field of struct.record.fields) {
      const fieldType = this.typeSpeller.getRustType(field.type!);
      if (field.isRecursive === "hard") {
        const boxedType = `std::option::Option<std::boxed::Box<${fieldType}>>`;
        this.push(`  pub _${field.name.text}: ${boxedType},\n`);
      } else {
        const fieldName = toStructFieldName(field.name.text);
        this.push(`  pub ${fieldName}: ${fieldType},\n`);
      }
    }
    this.push("}\n\n");

    // Getters for hard-recursive fields
    const hardRecursiveFields = struct.record.fields.filter(
      (f) => f.isRecursive === "hard",
    );
    if (hardRecursiveFields.length > 0) {
      this.push(`impl ${typeName} {\n`);
      for (const field of hardRecursiveFields) {
        const fieldName = toStructFieldName(field.name.text);
        const fieldType = this.typeSpeller.getRustType(field.type!);
        this.push(`  pub fn ${fieldName}(&self) -> &${fieldType} {\n`);
        this.push(`    match &self._${field.name.text} {\n`);
        this.push(`      Some(boxed) => boxed.as_ref(),\n`);
        this.push(`      None => ${fieldType}_default(),\n`);
        this.push("    }\n");
        this.push("  }\n");
      }
      this.push("}\n\n");
    }

    // Static default instance
    this.push(
      `static ${typeName}_DEFAULT: std::sync::LazyLock<${typeName}> = std::sync::LazyLock::new(|| ${typeName} {\n`,
    );
    for (const field of struct.record.fields) {
      if (field.isRecursive === "hard") {
        this.push(`  _${field.name.text}: None,\n`);
        continue;
      } else {
        const fieldName = toStructFieldName(field.name.text);
        const defaultExpr = this.typeSpeller.getDefaultExpr(field.type!);
        this.push(`  ${fieldName}: ${defaultExpr},\n`);
      }
    }
    this.push("});\n\n");

    // Default accessor function
    this.push(`pub fn ${typeName}_default() -> &'static ${typeName} {\n`);
    this.push(`  &${typeName}_DEFAULT\n`);
    this.push("}\n\n");
  }

  private writeEnum(record: RecordLocation): void {
    const typeName = getTypeName(record);
    this.push(`#[derive(std::clone::Clone)]\n`);
    this.push(`pub enum ${typeName} {\n`);
    this.push(`  Unknown,\n`);
    this.push("}\n\n");
  }

  private writeMethod(method: Method): void {}

  private writeConstant(constant: Constant): void {}

  private getKeyedArrayHelper(field: Field): KeyedArrayHelper | null {
    const type = field.type!;
    if (type.kind !== "array") {
      return null;
    }
    const { key } = type;
    if (!key) {
      return null;
    }
    const searchMethodName = convertCase(field.name.text, "UpperCamel")
      .concat("_SearchBy")
      .concat(
        key.path.map((p) => convertCase(p.name.text, "UpperCamel")).join(""),
      );
    const keyAccessor = "e.".concat(
      key.path
        .map((p) => toStructFieldName(p.name.text).concat("()"))
        .join("."),
    );
    const { typeSpeller } = this;
    const itemType = typeSpeller.getRustType(type.item);
    const makeMapType = (comp: string): string => `map[${comp}]${itemType}`;
    const { keyType } = key;
    switch (keyType.kind) {
      case "primitive": {
        switch (keyType.primitive) {
          case "bool":
          case "int32":
          case "int64":
          case "float32":
          case "float64":
          case "string":
          case "hash64": {
            // The simple case: the key type is already comparable.
            const comparableType = typeSpeller.getRustType(keyType);
            return {
              searchMethodName: searchMethodName,
              itemType: itemType,
              mapType: makeMapType(comparableType),
              exposedKeyType: comparableType,
              itemToComparableExpr: keyAccessor,
              exposedKeyToComparableExpr: "k",
            };
          }
          case "timestamp":
            return {
              searchMethodName: searchMethodName,
              itemType: itemType,
              mapType: makeMapType("int64"),
              exposedKeyType: "time.Time",
              itemToComparableExpr: keyAccessor.concat(".UnixMilli()"),
              exposedKeyToComparableExpr: "k.UnixMilli()",
            };
          case "bytes":
            return {
              searchMethodName: searchMethodName,
              itemType: itemType,
              mapType: makeMapType("string"),
              exposedKeyType: "skir_client.Bytes",
              itemToComparableExpr: keyAccessor.concat(".Hex()"),
              exposedKeyToComparableExpr: "k.Hex()",
            };
        }
        break;
      }
      case "record": {
        const comparableType = typeSpeller.getRustType(keyType).concat("_kind");
        return {
          searchMethodName: searchMethodName,
          itemType: itemType,
          mapType: makeMapType(comparableType),
          exposedKeyType: comparableType,
          itemToComparableExpr: keyAccessor,
          exposedKeyToComparableExpr: "k",
        };
      }
    }
  }

  private isStructType(type: ResolvedType): boolean {
    return (
      type.kind === "record" &&
      this.typeSpeller.recordMap.get(type.key)?.record.recordType === "struct"
    );
  }

  private pushSeparator(header: string): void {
    this.push(`// ${"=".repeat(78)}\n`);
    this.push(`// ${header}\n`);
    this.push(`// ${"=".repeat(78)}\n\n`);
  }

  private push(...code: string[]): void {
    this.code += code.join("");
  }

  private joinLinesAndFixFormatting(): string {
    const indentUnit = "\t";
    let result = "";
    // The indent at every line is obtained by repeating indentUnit N times,
    // where N is the length of this array.
    const contextStack: Array<"{" | "(" | "[" | "<" | ":" | "."> = [];
    // Returns the last element in `contextStack`.
    const peakTop = (): string => contextStack.at(-1)!;
    const getMatchingLeftBracket = (r: "}" | ")" | "]" | ">"): string => {
      switch (r) {
        case "}":
          return "{";
        case ")":
          return "(";
        case "]":
          return "[";
        case ">":
          return "<";
      }
    };
    for (let line of this.code.split("\n")) {
      line = line.trim();
      if (line.length <= 0) {
        // Don't indent empty lines.
        result += "\n";
        continue;
      }

      const firstChar = line[0];
      switch (firstChar) {
        case "}":
        case ")":
        case "]":
        case ">": {
          const left = getMatchingLeftBracket(firstChar);
          while (contextStack.pop() !== left) {
            if (contextStack.length <= 0) {
              throw Error();
            }
          }
          break;
        }
        case ".": {
          if (peakTop() !== ".") {
            contextStack.push(".");
          }
          break;
        }
      }
      const indent =
        indentUnit.repeat(contextStack.length) +
        (line.startsWith("*") ? " " : "");
      result += `${indent}${line.trimEnd()}\n`;
      if (line.startsWith("/") || line.startsWith("*")) {
        // A comment.
        continue;
      }
      const lastChar = line.slice(-1);
      switch (lastChar) {
        case "{":
        case "(":
        case "[":
        case "<": {
          // The next line will be indented
          contextStack.push(lastChar);
          break;
        }
        case ":":
        case "=": {
          if (peakTop() !== ":") {
            contextStack.push(":");
          }
          break;
        }
        case ";":
        case ",": {
          if (peakTop() === "." || peakTop() === ":") {
            contextStack.pop();
          }
        }
      }
    }

    return (
      result
        // Remove spaces enclosed within curly brackets if that's all there is.
        .replace(/\{\s+\}/g, "{}")
        // Remove spaces enclosed within round brackets if that's all there is.
        .replace(/\(\s+\)/g, "()")
        // Remove spaces enclosed within square brackets if that's all there is.
        .replace(/\[\s+\]/g, "[]")
        // Remove empty line following an open curly bracket.
        .replace(/(\{\n *)\n/g, "$1")
        // Remove empty line preceding a closed curly bracket.
        .replace(/\n(\n *\})/g, "$1")
        // Coalesce consecutive empty lines.
        .replace(/\n\n\n+/g, "\n\n")
        .replace(/\n\n$/g, "\n")
    );
  }

  private readonly typeSpeller: TypeSpeller;
  private code = "";
}

interface KeyedArrayHelper {
  /** Name of the generated Search method. */
  readonly searchMethodName: string;
  /** Item (Go) type. */
  readonly itemType: string;
  /** Go type of the internal map. */
  readonly mapType: string;
  /** Key (Go) type exposed to the user. */
  readonly exposedKeyType: string;
  /** Go expression for extracting a comparable key from an item (e). */
  readonly itemToComparableExpr: string;
  /** Go expression for extracting a comparable key from an exposed key (k). */
  readonly exposedKeyToComparableExpr: string;
}

function toGoStringLiteral(input: string): string {
  const escaped = input
    .replace(/\\/g, "\\\\") // Escape backslashes
    .replace(/"/g, '\\"') // Escape double quotes
    .replace(/\n/g, "\\n") // Escape newlines
    .replace(/\r/g, "\\r") // Escape carriage returns
    .replace(/\t/g, "\\t"); // Escape tabs
  return `"${escaped}"`;
}

function tryGetGoLiteral(constant: Constant): string | null {
  const type = constant.type!;
  if (type.kind !== "primitive") {
    return null;
  }
  const valueAsDenseJson = constant.valueAsDenseJson!;
  switch (type.primitive) {
    case "bool":
      return valueAsDenseJson ? "true" : "false";
    case "int32":
    case "int64":
    case "hash64":
    case "float32":
    case "float64": {
      const maybeQuoted = valueAsDenseJson.toString();
      if (
        maybeQuoted === "Infinity" ||
        maybeQuoted === "-Infinity" ||
        maybeQuoted === "NaN"
      ) {
        return null;
      } else {
        return maybeQuoted.startsWith('"') && maybeQuoted.endsWith('"')
          ? maybeQuoted.slice(1, -1)
          : maybeQuoted;
      }
    }
    case "string":
      return toGoStringLiteral(valueAsDenseJson as string);
  }
  return null;
}

function commentify(textOrLines: string | readonly string[]): string {
  const text = (
    typeof textOrLines === "string" ? textOrLines : textOrLines.join("\n")
  )
    .trim()
    .replace(/\n{3,}/g, "\n\n");
  if (text.length <= 0) {
    return "";
  }
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? `// ${line}\n` : `//\n`))
    .join("");
}

function docToCommentText(doc: Doc): string {
  return doc.pieces
    .map((p) => {
      switch (p.kind) {
        case "text":
          return p.text;
        case "reference":
          return "`" + p.referenceRange.text.slice(1, -1) + "`";
      }
    })
    .join("");
}

export const GENERATOR = new RustCodeGenerator();
