// defaultRef() -> default_ref()?
// find_by_key_or_default()?
// TODO: make unreocgnized fields Option, instead of defining the Option in the client lib as a typedef
// Possibly add the `kind` to the enum if needed by KeyedVec
// Possibly add the GetKey implementations...

import {
  type CodeGenerator,
  type Constant,
  convertCase,
  type Doc,
  type Field,
  type FieldPath,
  type Method,
  type RecordKey,
  type RecordLocation,
  type ResolvedType,
} from "skir-internal";
import { z } from "zod";
import {
  getTypeName,
  isUpperCasedKeyword,
  toStructFieldName,
} from "./naming.js";
import { collectRustModuleSpecs, RustModuleSpec } from "./rust_module_spec.js";
import { TypeSpeller } from "./type_speller.js";
import { createKeyedArrayContext, KeyedArrayContext } from "./keyed_array_context.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

class RustCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-rust-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap, config } = input;
    const keyedArrayContext = createKeyedArrayContext(input.modules);
    const rustModuleSpecs = collectRustModuleSpecs(input.modules);
    const outputFiles = rustModuleSpecs.map((moduleSpec) => (
      {
        path: moduleSpec.path,
        code: new RustSourceFileGenerator(
          moduleSpec,
          recordMap,
          keyedArrayContext,
          config,
        ).generate(),
      }
    ));
    return { files: outputFiles };
  }
}

// Generates the code for one Rust file.
class RustSourceFileGenerator {
  constructor(
    private readonly moduleSpec: RustModuleSpec,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
    private readonly keyedArrayContext: KeyedArrayContext,
    private readonly config: Config,
  ) {
    this.typeSpeller = new TypeSpeller(recordMap, moduleSpec.skirModule?.path);
  }

  generate(): string {
    // const packageName = skirModulePathToSkiroutPath(this.inModule.path);

    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.push(
      `#![allow(nonstandard_style)]

      //  ______                        _               _  _  _
      //  |  _  \\                      | |             | |(_)| |
      //  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
      //  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _\` || || __|
      //  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_ 
      //  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|
      //
      // Generated by skir-rust-gen
      // Home: https://github.com/gepheum/skir-rust-gen
      //
      // To install the Skir client library, run:
      //   cargo add skir-rust-client
      `,
    );

    for (const childModuleName of this.moduleSpec.childModuleNames) {
      this.push(`pub mod ${childModuleName};\n`);
    }

    this.push("\n");

    const skirModule = this.moduleSpec.skirModule;
    if (skirModule) {
      for (const record of skirModule.records) {
        const { recordType } = record.record;
        if (recordType === "struct") {
          this.writeStruct(record);
        } else {
          this.writeEnum(record);
        }
      }

      if (skirModule.methods.length) {
        this.pushSeparator("Methods");
        for (const method of skirModule.methods) {
          this.writeMethod(method);
        }
      }

      if (skirModule.constants.length) {
        this.pushSeparator("Constants");
        for (const constant of skirModule.constants) {
          this.writeConstant(constant);
        }
      }
    }

    return this.joinLinesAndFixFormatting();
  }

  private writeStruct(struct: RecordLocation): void {
    this.pushSeparator(
      "struct ".concat(
        struct.recordAncestors.map((r) => r.name.text).join("."),
      ),
    );
    const typeName = getTypeName(struct);
    const allFieldsUseRustDefault = struct.record.fields.every(
      (f) =>
        f.isRecursive === "hard" ||
        this.typeSpeller.skirDefaultIsRustDefault(f.type!),
    );
    const deriveList = allFieldsUseRustDefault
      ? `std::fmt::Debug, std::clone::Clone, std::cmp::PartialEq, std::default::Default`
      : `std::fmt::Debug, std::clone::Clone, std::cmp::PartialEq`;
    this.push(`#[derive(${deriveList})]\n`);
    this.push(`pub struct ${typeName} {\n`);
    for (const field of struct.record.fields) {
      const fieldType = this.typeSpeller.getRustType(field.type!);
      if (field.isRecursive === "hard") {
        const boxedType = `std::option::Option<std::boxed::Box<${fieldType}>>`;
        this.push(`  pub _${field.name.text}_rec: ${boxedType},\n`);
      } else {
        const fieldName = toStructFieldName(field.name.text);
        this.push(`  pub ${fieldName}: ${fieldType},\n`);
      }
    }
    this.push(
      `  pub _unrecognized: crate::skir_client::unrecognized::UnrecognizedFields<${typeName}>,\n`,
    );
    this.push("}\n\n");

    // impl block: defaultRef() + getters for hard-recursive fields
    const hardRecursiveFields = struct.record.fields.filter(
      (f) => f.isRecursive === "hard",
    );
    this.push(`impl ${typeName} {\n`);

    // defaultRef()
    this.push(`  pub fn defaultRef() -> &'static ${typeName} {\n`);
    this.push(
      `    static D: std::sync::LazyLock<${typeName}> = std::sync::LazyLock::new(${typeName}::default);\n`,
    );
    this.push("    &D\n");
    this.push("  }\n");

    // Getters for hard-recursive fields
    for (const field of hardRecursiveFields) {
      const fieldName = toStructFieldName(field.name.text);
      const fieldType = this.typeSpeller.getRustType(field.type!);
      this.push(`  pub fn ${fieldName}(&self) -> &${fieldType} {\n`);
      this.push(`    match &self._${field.name.text}_rec {\n`);
      this.push(`      Some(boxed) => boxed.as_ref(),\n`);
      this.push(`      None => ${fieldType}::defaultRef(),\n`);
      this.push("    }\n");
      this.push("  }\n");
    }

    this.push("}\n\n");

    // Manual Default impl — only needed when #[derive(Default)] can't be used.
    if (!allFieldsUseRustDefault) {
      this.push(`impl std::default::Default for ${typeName} {\n`);
      this.push(`  fn default() -> Self {\n`);
      this.push(`    ${typeName} {\n`);
      for (const field of struct.record.fields) {
        if (field.isRecursive === "hard") {
          this.push(`      _${field.name.text}_rec: None,\n`);
        } else {
          const fieldName = toStructFieldName(field.name.text);
          const defaultExpr = this.typeSpeller.getDefaultExpr(field.type!);
          this.push(`      ${fieldName}: ${defaultExpr},\n`);
        }
      }
      this.push(`      _unrecognized: None,\n`);
      this.push("    }\n");
      this.push("  }\n");
      this.push("}\n\n");
    }

    // Write a GetKey impl for each keyed array that has this struct as item type.
    const keyedArrayExtractors =
      this.keyedArrayContext.recordKeyToKeyExtractors.get(struct.record.key);
    for (const fieldPath of keyedArrayExtractors?.values() ?? []) {
      const implName = typeName.concat("_by").concat(fieldPath.path.map((p) => convertCase(p.name.text, "UpperCamel")).join("_"));
      this.push(`struct ${implName};\n\n`);
      this.push(`impl crate::skir_client::keyed_vec::GetKey for ${implName} {\n`);
      this.push(`  type Item = ${typeName};\n`);
      this.push("}\n\n");
    }
  }

  private writeEnum(record: RecordLocation): void {
    this.pushSeparator(
      "enum ".concat(record.recordAncestors.map((r) => r.name.text).join(".")),
    );
    const typeName = getTypeName(record);
    this.push(
      `#[derive(std::fmt::Debug, std::clone::Clone, std::cmp::PartialEq)]\n`,
    );
    this.push(`pub enum ${typeName} {\n`);
    this.push(
      `  Unknown(crate::skir_client::unrecognized::UnrecognizedVariant<${typeName}>),\n`,
    );
    const variantNamesNeedSuffix = doVariantNamesNeedSuffix(
      record.record.fields,
    );
    for (const variant of record.record.fields) {
      const variantName = convertCase(variant.name.text, "UpperCamel").concat(
        variantNamesNeedSuffix ? (variant.type ? "Wrapper" : "Const") : "",
      );
      if (variant.type) {
        const variantType = variant.type!;
        let valueRustType = this.typeSpeller.getRustType(variantType);
        if (doesWrapperVariantNeedBoxing(variantType)) {
          valueRustType = `std::boxed::Box<${valueRustType}>`;
        }
        this.push(`  ${variantName}(${valueRustType}),\n`);
      } else {
        this.push(`  ${variantName},\n`);
      }
    }
    this.push("}\n\n");

    this.push(`impl std::default::Default for ${typeName} {\n`);
    this.push(`  fn default() -> Self {\n`);
    this.push(`    ${typeName}::Unknown(None)\n`);
    this.push("  }\n");
    this.push("}\n\n");
  }

  private writeMethod(method: Method): void {}

  private writeConstant(constant: Constant): void {}

  private pushSeparator(header: string): void {
    this.push(`// ${"=".repeat(78)}\n`);
    this.push(`// ${header}\n`);
    this.push(`// ${"=".repeat(78)}\n\n`);
  }

  private push(...code: string[]): void {
    this.code += code.join("");
  }

  private joinLinesAndFixFormatting(): string {
    const indentUnit = "    ";
    let result = "";
    // The indent at every line is obtained by repeating indentUnit N times,
    // where N is the length of this array.
    const contextStack: Array<"{" | "(" | "[" | "<" | ":" | "."> = [];
    // Returns the last element in `contextStack`.
    const peakTop = (): string => contextStack.at(-1)!;
    const getMatchingLeftBracket = (r: "}" | ")" | "]" | ">"): string => {
      switch (r) {
        case "}":
          return "{";
        case ")":
          return "(";
        case "]":
          return "[";
        case ">":
          return "<";
      }
    };
    for (let line of this.code.split("\n")) {
      line = line.trim();
      if (line.length <= 0) {
        // Don't indent empty lines.
        result += "\n";
        continue;
      }

      const firstChar = line[0];
      switch (firstChar) {
        case "}":
        case ")":
        case "]":
        case ">": {
          const left = getMatchingLeftBracket(firstChar);
          while (contextStack.pop() !== left) {
            if (contextStack.length <= 0) {
              throw Error();
            }
          }
          break;
        }
        case ".": {
          if (peakTop() !== ".") {
            contextStack.push(".");
          }
          break;
        }
      }
      const indent =
        indentUnit.repeat(contextStack.length) +
        (line.startsWith("*") ? " " : "");
      result += `${indent}${line.trimEnd()}\n`;
      if (line.startsWith("/") || line.startsWith("*")) {
        // A comment.
        continue;
      }
      const lastChar = line.slice(-1);
      switch (lastChar) {
        case "{":
        case "(":
        case "[":
        case "<": {
          // The next line will be indented
          contextStack.push(lastChar);
          break;
        }
        case ":":
        case "=": {
          if (peakTop() !== ":") {
            contextStack.push(":");
          }
          break;
        }
        case ";":
        case ",": {
          if (peakTop() === "." || peakTop() === ":") {
            contextStack.pop();
          }
        }
      }
    }

    return (
      result
        // Remove spaces enclosed within curly brackets if that's all there is.
        .replace(/\{\s+\}/g, "{}")
        // Remove spaces enclosed within round brackets if that's all there is.
        .replace(/\(\s+\)/g, "()")
        // Remove spaces enclosed within square brackets if that's all there is.
        .replace(/\[\s+\]/g, "[]")
        // Remove empty line following an open curly bracket.
        .replace(/(\{\n *)\n/g, "$1")
        // Remove empty line preceding a closed curly bracket.
        .replace(/\n(\n *\})/g, "$1")
        // Coalesce consecutive empty lines.
        .replace(/\n\n\n+/g, "\n\n")
        .replace(/\n\n$/g, "\n")
    );
  }

  private readonly typeSpeller: TypeSpeller;
  private code = "";
}

function doVariantNamesNeedSuffix(variants: readonly Field[]): boolean {
  const seenNames = new Set<string>();
  for (const variant of variants) {
    const name = convertCase(variant.name.text, "UpperCamel");
    if (isUpperCasedKeyword(name) || seenNames.has(name)) {
      return true;
    }
    seenNames.add(name);
  }
  return false;
}

function doesWrapperVariantNeedBoxing(type: ResolvedType): boolean {
  switch (type.kind) {
    case "array":
      return false;
    case "optional":
      return doesWrapperVariantNeedBoxing(type.other);
    case "primitive":
      return false;
    case "record":
      return true;
  }
}

function toRustStringLiteral(input: string): string {
  const escaped = input
    .replace(/\\/g, "\\\\") // Escape backslashes
    .replace(/"/g, '\\"') // Escape double quotes
    .replace(/\n/g, "\\n") // Escape newlines
    .replace(/\r/g, "\\r") // Escape carriage returns
    .replace(/\t/g, "\\t"); // Escape tabs
  return `"${escaped}"`;
}

function tryGetGoLiteral(constant: Constant): string | null {
  const type = constant.type!;
  if (type.kind !== "primitive") {
    return null;
  }
  const valueAsDenseJson = constant.valueAsDenseJson!;
  switch (type.primitive) {
    case "bool":
      return valueAsDenseJson ? "true" : "false";
    case "int32":
    case "int64":
    case "hash64":
    case "float32":
    case "float64": {
      const maybeQuoted = valueAsDenseJson.toString();
      if (
        maybeQuoted === "Infinity" ||
        maybeQuoted === "-Infinity" ||
        maybeQuoted === "NaN"
      ) {
        return null;
      } else {
        return maybeQuoted.startsWith('"') && maybeQuoted.endsWith('"')
          ? maybeQuoted.slice(1, -1)
          : maybeQuoted;
      }
    }
    case "string":
      return toRustStringLiteral(valueAsDenseJson as string);
  }
  return null;
}

function commentify(textOrLines: string | readonly string[]): string {
  const text = (
    typeof textOrLines === "string" ? textOrLines : textOrLines.join("\n")
  )
    .trim()
    .replace(/\n{3,}/g, "\n\n");
  if (text.length <= 0) {
    return "";
  }
  return text
    .split("\n")
    .map((line) => (line.length > 0 ? `// ${line}\n` : `//\n`))
    .join("");
}

function docToCommentText(doc: Doc): string {
  return doc.pieces
    .map((p) => {
      switch (p.kind) {
        case "text":
          return p.text;
        case "reference":
          return "`" + p.referenceRange.text.slice(1, -1) + "`";
      }
    })
    .join("");
}

export const GENERATOR = new RustCodeGenerator();
